// <auto-generated />
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20230118230900_user_with_s")]
    partial class user_with_s
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoard.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThreadsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Body = "News",
                            ThreadsId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            PostId = 2,
                            Body = "Memes",
                            ThreadsId = 2,
                            UsersId = 2
                        },
                        new
                        {
                            PostId = 3,
                            Body = "Sports",
                            ThreadsId = 3,
                            UsersId = 3
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Threads", b =>
                {
                    b.Property<int>("ThreadsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ThreadsId");

                    b.ToTable("Threads");

                    b.HasData(
                        new
                        {
                            ThreadsId = 1,
                            Title = "News",
                            UsersId = 1
                        },
                        new
                        {
                            ThreadsId = 2,
                            Title = "Memes",
                            UsersId = 2
                        },
                        new
                        {
                            ThreadsId = 3,
                            Title = "Sports",
                            UsersId = 3
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Users", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsersId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UsersId = 1,
                            Name = "Chris"
                        },
                        new
                        {
                            UsersId = 2,
                            Name = "Yoonis"
                        },
                        new
                        {
                            UsersId = 3,
                            Name = "Robert"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
